kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

workspace:
  base: /go
  path: src/github.com/yourname/go-drone-hello-world

steps:
  - name: build_netdata
    image: ubuntu:18.04
    environment:
      LOCALPASS:
        from_secret: testpass
      VPSPASS:
        from_secret: vpspass
    volumes:
      - name: reports
        path: /var/reports
    commands:
      - rm -f /etc/apt/apt.conf.d/docker-clean
      - apt-get update -qqy && DEBIAN_FRONTEND=noninteractive apt-get -yq install git build-essential  debhelper dh-autoreconf dh-systemd dpkg-dev zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev libjson-c-dev libcups2-dev libipmimonitoring-dev libnetfilter-acct-dev libsnappy-dev libprotobuf-dev libprotoc-dev autogen autoconf automake pkg-config curl gcc g++ sshpass
      #- apt-get update -qqy && apt-get install -qq -y git build-essential  debhelper dh-autoreconf dh-systemd dpkg-dev zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev libjson-c-dev libcups2-dev libipmimonitoring-dev libnetfilter-acct-dev libsnappy-dev libprotobuf-dev libprotoc-dev autogen autoconf automake pkg-config curl gcc g++ sshpass
      - git clone https://github.com/netdata/netdata.git
      - cd netdata
      - git checkout tags/v1.16.1 -b local_1.16.1
      - sed -i 's/PREVIOUS_PACKAGE_VERSION/1.16.1/g' contrib/debian/changelog
      - sed -i 's/PREVIOUS_PACKAGE_DATE/Mon, 2 Sep 2019 23:09:59 +0000/g' contrib/debian/changelog
      - ln -s contrib/debian
      - dpkg-buildpackage -us -uc -rfakeroot
      - dpkg -i ../netdata_1.16.1_arm64.deb
      - mkdir ../debs
      - find /var/cache | grep deb$ | xargs -I % cp % ../debs/
      - cp ../netdata_1.16.1_arm64.deb ../debs
      - sshpass -p $VPSPASS scp -P2282 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ../netdata_1.16.1_arm64.deb root@209.141.35.192:/root/static
      - sshpass -p $VPSPASS scp -P2282 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ../debs/ root@209.141.35.192:/root/static

#  - name: build
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#
#  - name: run
#    image: golang
#    commands:
#      - go get
#      - go build -o output
#      - chmod +x output
#      - ./output

#volumes:
#  - name: reports
#    host:
#      path: /home/dev/work/src/github.com/cyantarek/drone-go-git-test/reports
